src/components/statistics/monthly/CompletionText/CompletionText.tsx
src/hooks/useMonthlyStatistics.ts
src/pages/statistics/MonthlyStatisticsPage.tsx

> 월간 통계 로직 스타일 분리
> #9
- useMonthlyStatistics.ts 훅 파일 추가
- CompletionText 컴포넌트 추가
- 월간 통계 페이지 리팩토링
>

Refactor/#9 - 월간 통계 로직 스타일 분리

---

src/components/home/NoList/NoList.tsx
src/components/home/index.ts
src/hooks/useHomePage.ts
src/pages/home/HomePage.tsx

> 메인(홈) 페이지 - 로직, 스타일 분리
- #4 
>

Feature/#4-메인(홈) 페이지 로직, 스타일 분리

---

src/hooks/useRegister.ts
src/pages/register/RegisterPage.tsx

> register 스타일, 로직 분리
> #8
- 로직 분리 훅 추가
- 리팩토링
>

Feature/#8 - Register 스타일, 로직 분리

---

src/components/housework/HouseworkForm/HouseworkForm.tsx
src/components/housework/TaskAssignmentContent/TaskAssignmentContent.tsx
src/components/housework/index.ts
src/hooks/useHouseworkStepOne.ts
src/hooks/useHouseworkStepTwo.ts
src/pages/housework/HouseWorkStepOnePage.tsx
src/pages/housework/HouseWorkStepTwoPage.tsx
src/store/useAddHouseWorkStore.ts
src/utils/convertStartTime.ts
src/utils/convertTimeToObject.ts

> 집안일 추가 페이지 - 로직, 스타일 분리
- #6 
- #3 
- 섹션 단위 컴포넌트 분리
- 로직을 훅으로 분리
- import 통합

Feature/#6-집안일 추가 페이지 로직, 스타일 분리

---

src/components/common/line/Line.tsx
src/components/my/AccountMenuItem/AccountMenuItem.tsx
src/components/my/LeaveGuide/LeaveGuide.tsx
src/hooks/useAccountManage.ts
src/hooks/useLeave.ts
src/hooks/useMy.ts
src/hooks/useMyEdit.ts
src/pages/my/AccountManagePage.tsx
src/pages/my/LeavePage.tsx
src/pages/my/MyPage.tsx
src/pages/my/MyPageEditPage.tsx

> 마이페이지 로직 스타일 분리
> #7
- 마이페이지
- 마이페이지 수정 페이지
- 회원관리 페이지
- 떠나기 페이지
>

Feature/#7 - 마이페이지 로직, 스타일 분리

---

public/robots.txt
public/sitemap.xml

> public 폴더에 sitemap.xml, robots.txt 파일 추가
- #13 
- #40 
- 위와 동일

Feature/#40 - sitemap.xml, robots.txt 추가

---

index.html
src/components/common/bottomNav/BottomNav.tsx
src/components/common/bottomNav/BottomNavBtn/BottomNavBtn.tsx
src/components/home/WeeklyDate/WeeklyDate.tsx
src/hooks/useHomePage.ts
src/pages/home/HomePage.tsx

> 메인 페이지
> 바텀 네비게이션
- 렌더링 최적화
- #17 
- #21 
- 위 내용과 같음

Feature/#21 - 메인 페이지 렌더링 최적화

---

src/hooks/useGroupCreate.ts
src/pages/group/GroupCreatePage.tsx

> 그룹 생성 페이지 - 로직 분리
- #3 
- #5 
-  #49 
- useGroupCreate 파일 추가

Feature/#49 - 그룹 생성 페이지 로직 분리

---

src/components/groupSelect/GroupList/GroupList.tsx
src/hooks/useGroupSelect.ts
src/pages/group/GroupSelectPage.tsx

>그룹 선택 페이지 - 스타일, 로직 분리
- #3 
- #5 
- #51 
- GroupList 컴포넌트 추가
- 로직을 훅으로 분리

Feature/#51 - 그룹 선택 페이지 스타일, 로직 분리

---

src/hooks/useGroupCreate.ts
src/pages/group/GroupCreatePage.tsx

> 그룹 생성 페이지 - 성능 최적화
- #17 
- #22 
- #55 
- 2번의 api를 호출하는 handleNext 메모이제이션

Feature/#55 - 그룹 생성 페이지 성능 최적화

---

src/components/groupSelect/GroupList/GroupList.tsx
src/hooks/useGroupSelect.ts
src/pages/group/GroupSelectPage.tsx

> 그룹 선택 페이지 - 성능 최적화
- #17 
- #22 
- #57 
- 그룹 리스트 메모이제이션

Feature/#57- 그룹 선택 페이지 렌더링 최적화

---

src/components/groupSelect/GroupSelectTitle/GroupSelectTitle.tsx

> 그룹 선택 페이지 - 제목 줄 간격 업데이트
- #59 
- 줄 간격을 늘림
- as-is
- to-be
> 수정 할 사항있으면 말씀해주세요

Feature/#59 - 그룹 선택 페이지 제목 줄 간격 업데이트

---

src/components/housework/DueDateSheet/DueDateSheet.stories.ts
src/components/housework/DueDateSheet/DueDateSheet.tsx
src/components/housework/HouseWorkSheet/HouseWorkSheet.tsx
src/components/housework/HouseworkForm/HouseworkForm.tsx
src/components/housework/TimeControl/TimeControl.tsx
src/components/housework/TimeControl/TimePicker/TimePicker.tsx
src/components/housework/steps/Step1.tsx
src/components/housework/steps/Step2.tsx
src/hooks/useAddHouseWork.ts
src/pages/housework/AddHouseworkPage.tsx
src/store/useAddHouseWorkStore.ts

> 집안일 추가 및 수정에 있는 오류를 잡았습니다.
로딩 화면도 뜨게 수정했습니다.
>

Fix/#64 - fix add housework page

---

src/components/statistics/monthly/CompletionText/CompletionText.tsx
src/components/statistics/monthly/MonthlyGoodBad/MonthlyGoodBad.tsx
src/components/statistics/monthly/MonthlyGrass/MonthlyGrass.tsx
src/hooks/useMonthlyStatistics.ts
src/pages/statistics/MonthlyStatisticsPage.tsx

> 월간 통계 최적화
> #67
- 월간 통계 최적화
- useCallback 사용
- React.memo로 감싸기
>

Feature/#67 - 월간 통계 최적화

---

src/components/common/errorMessage/ErrorMessage.tsx
src/components/common/input/InputWithLabel.tsx
src/components/common/metaTags/MetaTags.tsx
src/components/common/profile/ProfileImg.tsx
src/hooks/useRegister.ts

> 회원가입 최적화
> #25
- 회원가입 최적화
- 초기 받아온 닉네임 검사 로직 추가 (이름이 처음부터 5글자가 넘는 경우 처리안되는 문제)
- 하위 컴포넌트 React.FC 코드 삭제 :props로 변경
>

Feature/#25 - 회원가입 최적화

---

src/components/common/alert/AlertDialogProps.tsx
src/components/common/header/Header.tsx
src/components/my/AccountInfo/AccountInfo.tsx
src/components/my/AccountSetBtn/AccountSetBtn.tsx
src/components/my/LeaveGuide/LeaveGuide.tsx
src/components/my/ProfileEditBtn/ProfileEditBtn.tsx
src/hooks/useMy.ts
src/hooks/useMyEdit.ts

> 마이페이지 최적화
> #24
- 마이페이지 최적화
- 마이페이지 편집 페이지 최적화
- 하위 컴포넌트 React.FC 삭제
>

Feature/#24 - 마이페이지 최적화

---

src/components/statistics/weekly/WeeklyCompletion/CompletionBarGraph/CompletionBarGraph.tsx
src/components/statistics/weekly/WeeklyCompletion/WeeklyCompletion.tsx
src/components/statistics/weekly/WeeklyRanking/WeeklyRanking.tsx
src/components/statistics/weekly/WeeklyStatAction/WeeklyStatActions.tsx
src/pages/statistics/WeeklyStatisticsPage.tsx

- 주간통계 페이지 화면 수정
- #77 
- 그룹 칭찬/찌르기 현황 텍스트 추가
- React.FC 제거
>

Feature/#77-주간통계 페이지 화면 수정

---

src/components/common/bottomSheet/BottomSheet.tsx
src/components/housework/DueDateSheet/DueDateSheet.tsx
src/store/useAddHouseWorkStore.ts

> 날짜 선택하고 확인 버튼 안 누르고 바텀시트 닫아버리면 초기화되도록 수정했습니다.
집안일 추가 
집안일 수정
모두 값 설정안하고 나가면 초기화되도록 수정
>

Feature/#83 - refactor select date

---

index.html

> ex) 메인페이지 - 라우트 연결
- #92 
- 사이트 소유 코드 추가
>

Feature/#92 - 네이버 서치 콘솔 등록

---

src/components/housework/steps/Step1.tsx
src/components/housework/steps/Step2.tsx

> ex) 메인페이지 - 라우트 연결
바텀시트와 lazy와 suspense를 통해 지연로딩을 했습니다.
> ex) #이슈번호, #이슈번호
>

Feature/#109 - 바텀시트 지연로딩 적용

---

src/hooks/useMy.ts
src/pages/my/AccountManagePage.tsx
src/types/apis/userApi.ts

> 소셜 로그인 화면에 표시
> #111
- user 타입 정의에 provider추가
- provider 화면에 표시
>

Feature/#111 - 마이페이지 소셜 로그인 연결 화면에 표시

---

public/sitemap.xml

> 사이트맵 수정
- #119 
- https://www.xml-sitemaps.com/
- 위 사이트에서 사이트맵 수정
>

Feature/#119 - 사이트맵 수정

---

src/hooks/useHomePage.ts

> 메인 페이지 - 푸시알림 실패 토스트
- #120 
- 푸시알림 실패시 토스트 출력
- 함수를 기능별로 분리

Feature/#120 - 푸시알림 실패 토스트

---

src/components/home/WeeklyDate/DateItem/DateItem.stories.tsx
src/components/home/WeeklyDate/DateItem/DateItem.tsx
src/components/home/WeeklyDate/WeeklyDate.tsx

> 메인 페이지 - 주간 캘린더 금일 표시
- #121 
- 주간 캘린더의 날짜 컴포넌트에 isToday 속성 추가
- isToday가 true라면 화면에 표시

Feature/#121 - 주간 캘린더 금일 표시

---

src/services/axiosInstance.ts

> 환경 변수 수정
- #129 
https://www.notion.so/344f8abba3804b1bbf69eb7b2de47c8e
위 노션 링크에 환경변수 파일 업로드해놓았습니다.
- FCM 환경변수 값도 변경되었어요
>

Feature/#129 - 개발계, 운영계 분리에 따른 환경 변수 수정

---

src/hooks/useLanding.ts

> 랜딩페이지 - 로그인 URL 환경변수 수정
- #128 
- 개발계, 운영계에 따라 리다이렉팅 주소 변경
>

Feature/#128 - 로그인 환경변수 수정

---

src/hooks/useLanding.ts

> 랜딩 페이지 - FCM 토큰 세션 스토리지 저장 코드 삭제
- #128 
위와 동일

Feature/#128 - fcm 토큰 세션 스토리지 저장 코드 삭제

---

src/components/common/profile/ProfileImg.tsx

> profileimg 컴포넌트 lazy loading 제거
>#134
lazy loading 제거
>

Feature/#134 - profileimg lazy loading 제거

---

src/components/landing/ServiceLogo.tsx
src/pages/LandingPage.tsx

> 랜딩 페이지 소셜 로그인 버튼 모션 제거 
> #138 
- 랜딩 페이지에서 소셜 로그인 버튼에는 모션 기능 수정 (시간 줄임)
>

Feature/#138 - 랜딩 페이지 소셜 로그인 버튼 모션 수정

---

src/hooks/useAddHouseWork.ts
src/services/housework/postHousework.ts
src/services/housework/putHousework.ts
src/store/useAddHouseWorkStore.ts
src/types/apis/houseworkApi.ts

> 집안일 추가할 때 status가 추가되어서 수정했습니다.
>

✨ Feat: 집안일 추가 로직에 status 추가

---

src/components/common/bottomSheet/BottomSheet.tsx
src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.stories.tsx
src/components/housework/ManagerSelectSheet/ManagerItem/ManagerItems.tsx
src/components/housework/ManagerSelectSheet/ManagerSelectSheet.stories.tsx
src/components/housework/ManagerSelectSheet/ManagerSelectSheet.tsx
src/components/housework/steps/Step1.tsx
src/components/housework/steps/Step2.tsx
src/hooks/useAddHouseWork.ts
src/pages/housework/AddHouseworkPage.tsx
src/services/housework/getTargetUserId.ts
src/services/housework/postAssignHouseworkAi.ts
src/types/apis/houseworkApi.ts

✨ Feat: AI 할당 기능 추가

---

src/hooks/usePresetSetting.ts

- 프리셋페이지 사용자정의 입력창 버튼 수정
- #144 
- useCallback 누락된 의존성 추가
>

Fix/#144 - 프리셋페이지 사용자정의 입력창 버튼 수정

---

src/components/landing/LoginButtons.tsx

> ex) 메인페이지 - 라우트 연결
> #147
- 네이버 버튼 부분 주석처리했습니다.
>

🐛 Fix: 네이버 버튼 숨김

---

src/components/landing/LoginButtons.tsx

> ex) 메인페이지 - 라우트 연결
#147
- 네이버 살림
>

🔧 Wrench: 네이버 살림

---

src/components/common/tab/Tab/Tab.tsx
src/components/groupSelect/GroupList/GroupList.tsx
src/components/home/GroupSelectSheet/GroupOptions/GroupOption.tsx
src/components/home/GroupSelectSheet/GroupOptions/GroupOptions.tsx
src/components/home/HomeHeader/GroupSelectBtn/GroupSelectBtn.tsx
src/components/home/WeeklyDateAndTab.tsx
src/hooks/useGroupSelect.ts
src/hooks/useHomePage.ts
src/pages/group/GroupSelectPage.tsx
src/pages/home/HomePage.tsx
src/services/group/groupQuery.ts
src/services/housework/houseworkQuery.ts

> 메인 페이지 훅
- #161 
- useHomePage에 있는 get 함수를 useQuery로 정의해 사용하는 컴포넌트에서 직접 사용하도록 변경
>

Feature/#161 homepage 훅 tanstack query로 부분 교체

---

src/hooks/useNotification.ts
src/services/fcm/deleteFcmToken.ts
src/services/fcm/fcmMutation.ts
src/services/fcm/postFcmCheck.ts
src/types/apis/fcmApi.ts
src/utils/fcm.ts

> fcm 토큰 활성화 체크 
> #159
- fcm 토큰 활성화 체크 api추가 및 타입 추가
- api 바탕으로 toggle 상태 수정
>

Feature/#159 - fcm 토큰 활성화 체크 

---

src/utils/dateUtils.ts

> 날짜 undefined 오류 수정
> #172
날짜 undefined 오류 수정
>

Fix/#172 - 날짜 undefined 오류 수정

---

src/hooks/useWeeklyStatistics.ts
src/services/statistics/getWeeklyScore.ts

> 주간 통계 랭킹 데이터 초기화 코드 추가
> #180 
주간 통계 랭킹 데이터 초기화 코드 추가
>

Fix/#180 - 주간 통계 랭킹 데이터 초기화 코드 추가 
